title: Programación en R
description: Materia electiva - 2017
show_downloads: ["true"]

# Build settings
markdown: kramdown
exclude: ["Gemfile", "Gemfile.lock", ".gitignore", "Rakefile", "config.ru", "vendor", "TODO"]
